version: '3'
services:
  db:
    container_name: enrollment-db
    image: 'postgres:16'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=enrollment
  app:
    container_name: enrollment-app
    image: 'enrollment-be:1.0'
    build:
      context: ./enrollment-system-api
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/enrollment
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update